### ISSUE TITLE
Just curious about your motivation for creating this and benefits/drawbacks vs Three/Babylon

### ISSUE THREAD

**Issue by MeoMix** [jnsmalm/pixi3d#147]

**Comment by jnsmalm** [comment]
I have used PixiJS a lot in my professional career and wanted a easy way to just "throw in and animate some 3d models". I wanted it to play nice with rest off PixiJS without having to deal with hacking WebGL state back and forth. I also though it would be a fun challenge as a project.

Pixi3D is a benefit to use if you already like and use the PixiJS API, because it's the same. If you instead need all the features of Three/Babylon pick that instead. Those libs also have a lot more people working on them.
